### ISSUE TITLE
End of the crash course ?

### ISSUE THREAD

**Issue by clover21** [Fagrell/qml-editor#2]
Hi, I found the beginning of the crash course very interesting, but it's been 2 year since part 7.
Will the end of the series be written one day ?

**Comment by Fagrell** [comment]
Hey! Sorry I've been super busy in the last few years and haven't really had time to update the blog nor this project. That said, I plan to pick it up again next year and update the posts with the latest and greatest (including Qt 6.0). I'll also try to publish between 6-12 posts a year. Thanks for the interested!
